services:
  db:
    image: postgres:17
    container_name: data-store
    restart: always    
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./data/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data     

  fhir:
    image: "hapiproject/hapi:latest"
    container_name: fhir-server
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./hapi.application.yaml:/app/config/application.yaml
    depends_on:
      - db

volumes:
  pgdata:
